version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: registre.apps.ul-pca-pr-ul01.ulaval.ca/ul-val-genovalia-pr/ontology-search-dev:latest
    env_file:
      - path: local.env
        required: false
      - path: .env
        required: false
    environment:
      DJANGO_SETTINGS_MODULE: settings.dev
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    env_file:
      - path: local.env
        required: false
      - path: .env
        required: false

  redis:
    image: redis:6.2.4
